# Generated by Django 5.0.4 on 2024-05-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('json_schema', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edgetype')),
                ('node_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_a', to='api.node')),
                ('node_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_b', to='api.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nodetype'),
        ),
        migrations.AddField(
            model_name='edgetype',
            name='node_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_a', to='api.nodetype'),
        ),
        migrations.AddField(
            model_name='edgetype',
            name='node_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_b', to='api.nodetype'),
        ),
    ]
